// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolManagement.API.Data;

#nullable disable

namespace SchoolManagement.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.API.Models.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxMarks")
                        .HasColumnType("integer");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 11, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5364),
                            Deadline = new DateTime(2026, 8, 21, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5350),
                            Description = "Solve the following quadratic equations and show all working steps. Problems cover factoring, completing the square, and the quadratic formula.",
                            MaxMarks = 100,
                            Status = 1,
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000001"),
                            TeacherId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Title = "Algebra Basics - Quadratic Equations",
                            UpdatedAt = new DateTime(2026, 8, 11, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5366)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 9, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5379),
                            Deadline = new DateTime(2026, 8, 19, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5376),
                            Description = "Write a 500-word argumentative essay on the topic: 'Technology has more benefits than drawbacks in modern education.' Support your argument with evidence and examples.",
                            MaxMarks = 50,
                            Status = 1,
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000002"),
                            TeacherId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Title = "Essay Writing - Argumentative Essay",
                            UpdatedAt = new DateTime(2026, 8, 9, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5381)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 30, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5393),
                            Deadline = new DateTime(2026, 8, 12, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5390),
                            Description = "Complete the problem set on Newton's three laws of motion. Include free-body diagrams where applicable.",
                            MaxMarks = 80,
                            Status = 2,
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000003"),
                            TeacherId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Title = "Newton's Laws of Motion - Problem Set",
                            UpdatedAt = new DateTime(2026, 7, 30, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5394)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 13, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5405),
                            Deadline = new DateTime(2026, 8, 24, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5403),
                            Description = "Complete exercises on converting fractions to decimals, adding fractions with different denominators, and word problems.",
                            MaxMarks = 60,
                            Status = 1,
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000006"),
                            TeacherId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Title = "Fractions and Decimals",
                            UpdatedAt = new DateTime(2026, 8, 13, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5407)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5427),
                            Deadline = new DateTime(2026, 8, 28, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5424),
                            Description = "This assignment is in draft. Content to be finalized.",
                            MaxMarks = 70,
                            Status = 0,
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000004"),
                            TeacherId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Title = "Introduction to Chemical Bonding",
                            UpdatedAt = new DateTime(2026, 8, 14, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5428)
                        });
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TuitionFee")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 14, 15, 46, 14, 680, DateTimeKind.Utc).AddTicks(5744),
                            Description = "Grade 6",
                            IsActive = true,
                            Name = "Class 6",
                            TuitionFee = 1500m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 14, 15, 46, 14, 680, DateTimeKind.Utc).AddTicks(5757),
                            Description = "Grade 7",
                            IsActive = true,
                            Name = "Class 7",
                            TuitionFee = 1800m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 14, 15, 46, 14, 680, DateTimeKind.Utc).AddTicks(5781),
                            Description = "Grade 10 - Senior Secondary",
                            IsActive = true,
                            Name = "Class 10",
                            TuitionFee = 2500m
                        });
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "MATH101",
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 14, 680, DateTimeKind.Utc).AddTicks(6102),
                            Description = "Core mathematics",
                            IsActive = true,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "MATH101",
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 14, 680, DateTimeKind.Utc).AddTicks(6107),
                            Description = "Core mathematics",
                            IsActive = true,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "ENG101",
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 14, 680, DateTimeKind.Utc).AddTicks(6110),
                            Description = "English language & literature",
                            IsActive = true,
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "ENG101",
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 14, 680, DateTimeKind.Utc).AddTicks(6113),
                            Description = "English language & literature",
                            IsActive = true,
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "PHY101",
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 14, 680, DateTimeKind.Utc).AddTicks(6116),
                            Description = "General physics",
                            IsActive = true,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "CHEM101",
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 14, 680, DateTimeKind.Utc).AddTicks(6119),
                            Description = "General chemistry",
                            IsActive = true,
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "ICT101",
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 14, 680, DateTimeKind.Utc).AddTicks(6122),
                            Description = "Information & Communications Technology",
                            IsActive = true,
                            Name = "ICT"
                        });
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<int?>("Marks")
                        .HasColumnType("integer");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3530c972-b4fe-4db8-85df-61199f54ea8f"),
                            Answer = "1) x² - 5x + 6 = 0 → (x-2)(x-3) = 0 → x = 2 or x = 3\n2) 2x² + 7x + 3 = 0 → x = (-7 ± √(49-24))/4 → x = -1/2 or x = -3\n3) x² - 9 = 0 → (x-3)(x+3) = 0 → x = ±3",
                            AssignmentId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Feedback = "Excellent work! All solutions are correct. Your use of factoring in problem 1 and 3 is efficient. In problem 2, consider showing the discriminant calculation more explicitly.",
                            Marks = 88,
                            Status = 3,
                            StudentId = new Guid("30000000-0000-0000-0000-000000000004"),
                            SubmittedAt = new DateTime(2026, 8, 12, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5587),
                            UpdatedAt = new DateTime(2026, 8, 12, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5590)
                        },
                        new
                        {
                            Id = new Guid("45fde33b-090f-4401-bc26-65ebb72e5a92"),
                            Answer = "1) x = 2 or x = 3\n2) x = -0.5 or x = -3\n3) x = 3 or x = -3\n(Solved using quadratic formula for all)",
                            AssignmentId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Status = 2,
                            StudentId = new Guid("30000000-0000-0000-0000-000000000005"),
                            SubmittedAt = new DateTime(2026, 8, 13, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5610),
                            UpdatedAt = new DateTime(2026, 8, 13, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5612)
                        },
                        new
                        {
                            Id = new Guid("d891cff1-0590-43e2-bd8a-839356d3cad2"),
                            Answer = "Technology has revolutionized education in countless ways. From interactive learning platforms to instant access to global resources, the benefits far outweigh the challenges. While critics point to screen time concerns and digital distractions, a structured approach to technology integration enables personalized learning, enhances collaboration, and prepares students for a digital workforce...",
                            AssignmentId = new Guid("40000000-0000-0000-0000-000000000002"),
                            Status = 1,
                            StudentId = new Guid("30000000-0000-0000-0000-000000000004"),
                            SubmittedAt = new DateTime(2026, 8, 14, 9, 46, 18, 207, DateTimeKind.Utc).AddTicks(5623),
                            UpdatedAt = new DateTime(2026, 8, 14, 9, 46, 18, 207, DateTimeKind.Utc).AddTicks(5626)
                        },
                        new
                        {
                            Id = new Guid("f7773fd0-4043-4110-8146-9f2762c7203b"),
                            Answer = "Newton's First Law: An object at rest stays at rest... [detailed answers]",
                            AssignmentId = new Guid("40000000-0000-0000-0000-000000000003"),
                            Feedback = "Good understanding of the first two laws. Work on applying the third law in complex systems.",
                            Marks = 72,
                            Status = 3,
                            StudentId = new Guid("30000000-0000-0000-0000-000000000004"),
                            SubmittedAt = new DateTime(2026, 8, 9, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5646),
                            UpdatedAt = new DateTime(2026, 8, 9, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5648)
                        });
                });

            modelBuilder.Entity("SchoolManagement.API.Models.TeacherAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherAssignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7073c50e-7080-4bbb-91ad-3d2c6efbe927"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(4854),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000001"),
                            TeacherId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("dc02e9a5-7042-4844-8aa7-3b17df20af24"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(4866),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000003"),
                            TeacherId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("4c8db5c2-1b41-4f42-85cc-cdbcf23d2e27"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(4875),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000006"),
                            TeacherId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b55b7c53-6d4f-456a-88fd-95cf76778e4d"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5081),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000002"),
                            TeacherId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("65da5580-27c5-415e-8f08-c94e732ba86e"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5103),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000007"),
                            TeacherId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("28b3d2bc-4b70-4c1f-8d3e-f5180a54b96b"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 14, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(5111),
                            SubjectId = new Guid("20000000-0000-0000-0000-000000000004"),
                            TeacherId = new Guid("30000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("SchoolManagement.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 8, 14, 15, 46, 14, 846, DateTimeKind.Utc).AddTicks(5011),
                            Email = "admin@school.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$5REohqOllGiuFkFsKa8D1.F5BcrlziMBWI4GL0VA5jEtO38eiQnj6",
                            Phone = "+1-555-0100",
                            Role = 0,
                            UpdatedAt = new DateTime(2025, 8, 14, 15, 46, 14, 846, DateTimeKind.Utc).AddTicks(5027)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 10, 14, 15, 46, 15, 7, DateTimeKind.Utc).AddTicks(3423),
                            Email = "teacher@school.com",
                            FullName = "John Smith",
                            IsActive = true,
                            PasswordHash = "$2a$11$9ajSVm5oqU4Bg4iT/QStkeaGglO/Df6XFuWuhak6CNT9kuxfNnIjy",
                            Phone = "+1-555-0101",
                            Role = 1,
                            UpdatedAt = new DateTime(2025, 10, 14, 15, 46, 15, 7, DateTimeKind.Utc).AddTicks(3440)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 14, 15, 46, 15, 205, DateTimeKind.Utc).AddTicks(2529),
                            Email = "sarah.johnson@school.com",
                            FullName = "Sarah Johnson",
                            IsActive = true,
                            PasswordHash = "$2a$11$.zGwUqXxQkaQmyHg6Vye/.pX7RbHyFH7BlFT4T/Jb4St25.e8vYwa",
                            Phone = "+1-555-0102",
                            Role = 1,
                            UpdatedAt = new DateTime(2025, 12, 14, 15, 46, 15, 205, DateTimeKind.Utc).AddTicks(2569)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 14, 15, 46, 15, 558, DateTimeKind.Utc).AddTicks(2504),
                            Email = "student@school.com",
                            FullName = "Alice Brown",
                            IsActive = true,
                            PasswordHash = "$2a$11$2TtwiuNppviN5AK0G2DKUubf2wvdxK55DHGMTuM2uvYfZwJB9WZR6",
                            Phone = "+1-555-0201",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 2, 14, 15, 46, 15, 558, DateTimeKind.Utc).AddTicks(2519)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 14, 15, 46, 15, 857, DateTimeKind.Utc).AddTicks(4242),
                            Email = "bob.davis@school.com",
                            FullName = "Bob Davis",
                            IsActive = true,
                            PasswordHash = "$2a$11$WTJyW/sbtp5VYIuuikrgs.bR81d0RCLnu9Q13ys7ZQsoFeKpmNFS.",
                            Phone = "+1-555-0202",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 2, 14, 15, 46, 15, 857, DateTimeKind.Utc).AddTicks(4257)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 14, 15, 46, 16, 195, DateTimeKind.Utc).AddTicks(4439),
                            Email = "carol.white@school.com",
                            FullName = "Carol White",
                            IsActive = true,
                            PasswordHash = "$2a$11$5KPrlSBbugrsSRjP6UNQVOssoClfeNySRLKDXj28VOOA.GHM2lBRy",
                            Phone = "+1-555-0203",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 3, 14, 15, 46, 16, 195, DateTimeKind.Utc).AddTicks(4458)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 14, 15, 46, 16, 541, DateTimeKind.Utc).AddTicks(7283),
                            Email = "david.martinez@school.com",
                            FullName = "David Martinez",
                            IsActive = true,
                            PasswordHash = "$2a$11$4BD9ioRn6dOdA7KNKIndGu8TWJnZq8tn4HJJNLuLMNlgqU8cEUBhC",
                            Phone = "+1-555-0204",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 3, 14, 15, 46, 16, 541, DateTimeKind.Utc).AddTicks(7309)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 4, 14, 15, 46, 16, 872, DateTimeKind.Utc).AddTicks(5871),
                            Email = "eva.garcia@school.com",
                            FullName = "Eva Garcia",
                            IsActive = true,
                            PasswordHash = "$2a$11$w9csFq.kDf5witgnu24LBO4R4uEega3TnUBxtucivPEw3wbAEKB7q",
                            Phone = "+1-555-0205",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 4, 14, 15, 46, 16, 872, DateTimeKind.Utc).AddTicks(5896)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 5, 14, 15, 46, 17, 229, DateTimeKind.Utc).AddTicks(2160),
                            Email = "michael.brown@school.com",
                            FullName = "Michael Brown",
                            IsActive = true,
                            PasswordHash = "$2a$11$DK5MZLjW2tjkR9Rk/lA13u6Hl5JhHqOeRfA1kSgXAs3pAYNlil4pO",
                            Phone = "+1-555-0103",
                            Role = 1,
                            UpdatedAt = new DateTime(2026, 5, 14, 15, 46, 17, 229, DateTimeKind.Utc).AddTicks(2183)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 5, 14, 15, 46, 17, 674, DateTimeKind.Utc).AddTicks(8614),
                            Email = "sophia.wilson@school.com",
                            FullName = "Sophia Wilson",
                            IsActive = true,
                            PasswordHash = "$2a$11$BORnNoAsRn1NvUcHAOyu5OKjIMda5//mJ7hMD2F/nOcs3mKA2zavC",
                            Phone = "+1-555-0206",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 5, 14, 15, 46, 17, 674, DateTimeKind.Utc).AddTicks(8644)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            ClassId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 5, 14, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(2675),
                            Email = "james.taylor@school.com",
                            FullName = "James Taylor",
                            IsActive = true,
                            PasswordHash = "$2a$11$lhk9qRgEvurpjoDmfVjS0OPg/jbljhAKQ/ywKmdO1QOK8/VFsDxsu",
                            Phone = "+1-555-0207",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 5, 14, 15, 46, 18, 207, DateTimeKind.Utc).AddTicks(2698)
                        });
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Assignment", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Subject", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagement.API.Models.Submission", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagement.API.Models.TeacherAssignment", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagement.API.Models.User", b =>
                {
                    b.HasOne("SchoolManagement.API.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
